@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Mar 09 14:18:27 +0800 2023
REM SW Build 3671981 on Fri Oct 14 05:00:03 MDT 2022
REM
REM IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim mb_preset_wrapper_behav -key {Behavioral:sim_1:Functional:mb_preset_wrapper} -tclbatch mb_preset_wrapper.tcl -protoinst "protoinst_files/bd_9e88.protoinst" -protoinst "protoinst_files/bd_b764.protoinst" -protoinst "protoinst_files/bd_c467.protoinst" -protoinst "protoinst_files/mb_preset.protoinst" -log simulate.log"
call xsim  mb_preset_wrapper_behav -key {Behavioral:sim_1:Functional:mb_preset_wrapper} -tclbatch mb_preset_wrapper.tcl -protoinst "protoinst_files/bd_9e88.protoinst" -protoinst "protoinst_files/bd_b764.protoinst" -protoinst "protoinst_files/bd_c467.protoinst" -protoinst "protoinst_files/mb_preset.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
