# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: constrs/top.xdc

# Block Designs: bd/mb_preset/mb_preset.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset || ORIG_REF_NAME==mb_preset} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_axi_timer_0_0/mb_preset_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_axi_timer_0_0 || ORIG_REF_NAME==mb_preset_axi_timer_0_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_axi_uartlite_0_0/mb_preset_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_axi_uartlite_0_0 || ORIG_REF_NAME==mb_preset_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_axi_iic_0_0/mb_preset_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_axi_iic_0_0 || ORIG_REF_NAME==mb_preset_axi_iic_0_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_axi_quad_spi_0_0/mb_preset_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_axi_quad_spi_0_0 || ORIG_REF_NAME==mb_preset_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_microblaze_0_0/mb_preset_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_microblaze_0_0 || ORIG_REF_NAME==mb_preset_microblaze_0_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_mig_7series_0_0/mb_preset_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_mig_7series_0_0 || ORIG_REF_NAME==mb_preset_mig_7series_0_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_dlmb_v10_0/mb_preset_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_dlmb_v10_0 || ORIG_REF_NAME==mb_preset_dlmb_v10_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_ilmb_v10_0/mb_preset_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_ilmb_v10_0 || ORIG_REF_NAME==mb_preset_ilmb_v10_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_dlmb_bram_if_cntlr_0/mb_preset_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_preset_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_ilmb_bram_if_cntlr_0/mb_preset_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_preset_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_lmb_bram_0/mb_preset_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_lmb_bram_0 || ORIG_REF_NAME==mb_preset_lmb_bram_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_xbar_0/mb_preset_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_xbar_0 || ORIG_REF_NAME==mb_preset_xbar_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_microblaze_0_axi_periph_0/mb_preset_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mb_preset_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_microblaze_0_axi_intc_0/mb_preset_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_preset_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_microblaze_0_xlconcat_0/mb_preset_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_microblaze_0_xlconcat_0 || ORIG_REF_NAME==mb_preset_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_mdm_1_0/mb_preset_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_mdm_1_0 || ORIG_REF_NAME==mb_preset_mdm_1_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_rst_mig_7series_0_100M_0/mb_preset_rst_mig_7series_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_rst_mig_7series_0_100M_0 || ORIG_REF_NAME==mb_preset_rst_mig_7series_0_100M_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_axi_smc_0/mb_preset_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_axi_smc_0 || ORIG_REF_NAME==mb_preset_axi_smc_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_rst_mig_7series_0_100M_1_0/mb_preset_rst_mig_7series_0_100M_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_rst_mig_7series_0_100M_1_0 || ORIG_REF_NAME==mb_preset_rst_mig_7series_0_100M_1_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_axi_ethernet_0_0/mb_preset_axi_ethernet_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_axi_ethernet_0_0 || ORIG_REF_NAME==mb_preset_axi_ethernet_0_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_axi_ethernet_0_dma_0/mb_preset_axi_ethernet_0_dma_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_axi_ethernet_0_dma_0 || ORIG_REF_NAME==mb_preset_axi_ethernet_0_dma_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_axi_ethernet_0_refclk_0/mb_preset_axi_ethernet_0_refclk_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_axi_ethernet_0_refclk_0 || ORIG_REF_NAME==mb_preset_axi_ethernet_0_refclk_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_axi_gpio_0_0/mb_preset_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_axi_gpio_0_0 || ORIG_REF_NAME==mb_preset_axi_gpio_0_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_axi_gpio_1_0/mb_preset_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_axi_gpio_1_0 || ORIG_REF_NAME==mb_preset_axi_gpio_1_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_axi_gpio_2_0/mb_preset_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_axi_gpio_2_0 || ORIG_REF_NAME==mb_preset_axi_gpio_2_0} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_system_ila_0_1/mb_preset_system_ila_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_system_ila_0_1 || ORIG_REF_NAME==mb_preset_system_ila_0_1} -quiet] -quiet

# IP: bd/mb_preset/ip/mb_preset_state_0_0/mb_preset_state_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_preset_state_0_0 || ORIG_REF_NAME==mb_preset_state_0_0} -quiet] -quiet

# XDC: c:/Users/guanxian/Desktop/xilinx-ac701-2022.2/xilinx-ac701-2022.2.gen/sources_1/bd/mb_preset/mb_preset_ooc.xdc
