# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /tmp/jenkins-BUILDS-hw_designs_builds-2022.2-297_xilinx-ac701/bsps/xilinx-ac701-2022.2/hw_proj/xilinx-ac701-2022.2/xilinx-ac701-2022.2.srcs/sources_1/bd/mb_preset/ip/mb_preset_mdm_1_0/mb_preset_mdm_1_0.xci
# IP: The module: 'mb_preset_mdm_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /tmp/jenkins-BUILDS-hw_designs_builds-2022.2-297_xilinx-ac701/bsps/xilinx-ac701-2022.2/hw_proj/xilinx-ac701-2022.2/xilinx-ac701-2022.2.gen/sources_1/bd/mb_preset/ip/mb_preset_mdm_1_0/mb_preset_mdm_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_preset_mdm_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /tmp/jenkins-BUILDS-hw_designs_builds-2022.2-297_xilinx-ac701/bsps/xilinx-ac701-2022.2/hw_proj/xilinx-ac701-2022.2/xilinx-ac701-2022.2.gen/sources_1/bd/mb_preset/ip/mb_preset_mdm_1_0/mb_preset_mdm_1_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_preset_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /tmp/jenkins-BUILDS-hw_designs_builds-2022.2-297_xilinx-ac701/bsps/xilinx-ac701-2022.2/hw_proj/xilinx-ac701-2022.2/xilinx-ac701-2022.2.srcs/sources_1/bd/mb_preset/ip/mb_preset_mdm_1_0/mb_preset_mdm_1_0.xci
# IP: The module: 'mb_preset_mdm_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /tmp/jenkins-BUILDS-hw_designs_builds-2022.2-297_xilinx-ac701/bsps/xilinx-ac701-2022.2/hw_proj/xilinx-ac701-2022.2/xilinx-ac701-2022.2.gen/sources_1/bd/mb_preset/ip/mb_preset_mdm_1_0/mb_preset_mdm_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_preset_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /tmp/jenkins-BUILDS-hw_designs_builds-2022.2-297_xilinx-ac701/bsps/xilinx-ac701-2022.2/hw_proj/xilinx-ac701-2022.2/xilinx-ac701-2022.2.gen/sources_1/bd/mb_preset/ip/mb_preset_mdm_1_0/mb_preset_mdm_1_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_preset_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
